# This rule is not used by the project loongcollector-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the infraflow.co.infraflow.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: loongcollector-operator
    app.kubernetes.io/managed-by: kustomize
  name: agentgroup-editor-role
rules:
- apiGroups:
  - infraflow.co.infraflow
  resources:
  - agentgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infraflow.co.infraflow
  resources:
  - agentgroups/status
  verbs:
  - get
