apiVersion: v1
kind: List

items:
  - apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: loongcollector-agent
      namespace: loongcollector-system
      labels:
        k8s-app: loongcollector-agent
    spec:
      selector:
        matchLabels:
          k8s-app: loongcollector-agent
      template:
        metadata:
          labels:
            k8s-app: loongcollector-agent
        spec:
          tolerations:
            - operator: Exists # deploy on all nodes
          containers:
            - name: loongcollector
              env:
                - name: ALIYUN_LOG_ENV_TAGS # add log tags from env
                  value: _node_name_|_node_ip_
                - name: _node_name_
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: spec.nodeName
                - name: _node_ip_
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.hostIP
                - name: cpu_usage_limit # loongcollector's self monitor cpu limit
                  value: "1"
                - name: mem_usage_limit # loongcollector's self monitor mem limit
                  value: "512"
                - name: default_access_key_id # accesskey id if you want to flush to SLS
                  valueFrom:
                    secretKeyRef:
                      name: loongcollector-secret
                      key: access_key_id
                      optional: true
                - name: default_access_key # accesskey secret if you want to flush to SLS
                  valueFrom:
                    secretKeyRef:
                      name: loongcollector-secret
                      key: access_key
                      optional: true
              image: >-
                sls-opensource-registry.cn-shanghai.cr.aliyuncs.com/loongcollector-community-edition/loongcollector:latest
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 1000m
                  memory: 1Gi
                requests:
                  cpu: 400m
                  memory: 384Mi
              volumeMounts:
                - name: run
                  mountPath: /var/run # for container runtime socket
                - name: root
                  mountPath: /logtail_host # for log access on the node
                  mountPropagation: HostToContainer
                  readOnly: true
                - name: checkpoint
                  mountPath: /usr/local/loongcollector/data # for checkpoint between container restart
                - name: loongcollector-config
                  mountPath: /usr/local/loongcollector/conf/instance_config/local # mount config dir
                  readOnly: true
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /usr/local/loongcollector/loongcollector_control.sh
                      - stop
                      - "3"
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /liveness
                  port: 7953
                  scheme: HTTP
                initialDelaySeconds: 3
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true
          volumes:
            - name: run
              hostPath:
                path: /var/run
                type: Directory
            - name: root
              hostPath:
                path: /
                type: Directory
            - name: checkpoint
              hostPath:
                path: /etc/loongcollector-loongcollector-ds/checkpoint
                type: DirectoryOrCreate
            - name: loongcollector-config
              configMap:
                defaultMode: 420
                name: loongcollector-config

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: config-server-config
      namespace: loongcollector-system
      # 这里需要添加label，用于正确获取config-server的cm
      labels:
        app: config-server
    data:
      configServerURL: "http://config-server:8899"

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loongcollector-config
      namespace: loongcollector-system
    data:
      loongcollector_config.json: |
        {
          "ilogtail_configserver_address": [
            "config-server:8899"
          ]
        }